# Generated by Django 3.0.8 on 2020-08-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True)),
            ],
        ),
    ]
