# Generated by Django 3.0.8 on 2020-08-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
    ]
