# Generated by Django 3.0.8 on 2020-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200829_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
